In [1]:
import numpy as np
from sklearn import svm

Create the training data, a vertical line and a horizontal line

In [2]:
up = np.array([[i,x] for i,x in zip((0 for _ in iter(int,1)), range(-10, 10))]).ravel()

In [8]:
up_2_right = np.array([[i,x] for i,x in zip(range(-10, 10), range(-15, 5))]).ravel()

In [9]:
left_to_right = np.array([[i,x] for i,x in zip(range(-10, 10), (0 for _ in iter(int,1)))]).ravel()

Create the SVC

In [10]:
clf = svm.SVC(gamma=0.0001, C=50, probability=True)

Fit the models to the classifier

In [11]:
clf.fit(np.array([up, up_2_right, left_to_right]), np.array(['up', 'up2right', 'l2r']))

SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='rbf',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [12]:
clf.decision_function([up, up_2_right, left_to_right])

array([[-0.28143197,  2.49999996,  0.78143202],
       [-0.26764516,  0.76764516,  2.5       ],
       [ 2.49999994, -0.26391024,  0.7639103 ]])

Simple prediction

In [13]:
clf.predict([left_to_right, up_2_right, up])

array(['l2r', 'up2right', 'up'], dtype='<U8')

Create some noisy data

In [14]:
noisy_data = np.array([
       [  1, -10],
       [  3,  -9],
       [ -4,  -9],
       [ -3,  -9],
       [  2,  -9],
       [  5,  -6],
       [  1,  -4],
       [  0,  -3],
       [  0,  -5],
       [  4,  -3],
       [  0,   2],
       [  6,   1],ZZ
       [  0,   4],
       [  0,   3],
       [ 11,   6],
       [ -6,   8],
       [  4,   6],
       [  0,   9],
       [  0,   8],
       [  0,  10]])

In [15]:
vertical = np.array([
       [ 132, -2861],
       [ 132, 2862],
       [ 132, 2864],
       [ 132, 2865],
       [ 132, 2866],
       [ 132, 2867],
       [ 132, 2868],
       [ 132, 2869],
       [ 132, 2870],
       [ 132, 2871],
       [ 132, 2872],
       [ 132, 2873],
       [ 132, 2874],
       [ 132, 2875],
       [ 132, 2876],
       [ 132, 2877],
       [ 132, 2878],
       [ 132, 2879],
       [ 132, 2880],
       [ 132, 2881]])

In [16]:
up_right_trend = np.array([
       [  98, 2862],
       [  99, 2862],
       [ 101, 2864],
       [ 102, 2865],
       [ 104, 2866],
       [ 105, 2867],
       [ 107, 2868],
       [ 108, 2870],
       [ 110, 2871],
       [ 111, 2872],
       [ 112, 2872],
       [ 114, 2874],
       [ 116, 2875],
       [ 117, 2877],
       [ 119, 2878],
       [ 121, 2880],
       [ 123, 2881],
       [ 125, 2883],
       [ 127, 2885],
       [ 129, 2887]])

In [17]:
clf.predict([noisy_data.ravel(), vertical.ravel(), up_right_trend.ravel()])

array(['up', 'up2right', 'up2right'], dtype='<U8')

In [18]:
vertical[:, 0] = 0
vertical

array([[    0, -2861],
       [    0,  2862],
       [    0,  2864],
       [    0,  2865],
       [    0,  2866],
       [    0,  2867],
       [    0,  2868],
       [    0,  2869],
       [    0,  2870],
       [    0,  2871],
       [    0,  2872],
       [    0,  2873],
       [    0,  2874],
       [    0,  2875],
       [    0,  2876],
       [    0,  2877],
       [    0,  2878],
       [    0,  2879],
       [    0,  2880],
       [    0,  2881]])

In [19]:
clf.predict([noisy_data.ravel(), vertical.ravel(), up_right_trend.ravel()])

array(['up', 'up2right', 'up2right'], dtype='<U8')

In [20]:
clf.decision_function([noisy_data.ravel(), vertical.ravel(), up_right_trend.ravel()])

array([[-0.33319767,  2.5       ,  0.83319767],
       [ 2.        ,  1.        ,  0.        ],
       [ 2.        ,  1.        ,  0.        ]])